### PR TITLE
Haxor Engine BunnyMark

### PR DESCRIPTION
**Pull request by eduardo-costa**
I adapted the benchmark to my engine!
http://haxor.xyz/demos/bunny-mark/

### CODE REVIEW

**Comment by larsiusprime** [comment]
Great!

One nitpick:

793 files is a looooooooooooooot for a simple benchmark. You should update your gitignore file to only commit the files necessary to build the project, and exclude the compiled result from the commit.

**Comment by eduardo-costa** [comment]
Sorry about that!
It is my cpp output I forgot to filter.
My Win32 version is broken though :/

**Comment by larsiusprime** [comment]
It's okay, for now you can just commit the targets that are working and note which ones aren't.

**Comment by larsiusprime** [comment]
Maybe you just want to ignore the entire "deploy" folder? In OpenFL we always exclude the "export" folder contents.

**Comment by eduardo-costa** [comment]
The cpp folder has files used in the buld like the STB lib and GL .h
files..
I tried to add them to ignore but tortoisegit didn't do that :/

Em qui, 20 de ago de 2015 20:29, Lars Doucet notifications@github.com
escreveu:

**Comment by posxposy** [comment]
Awesome, thanks!

**Pull request merged**
